import aKIDcalledMAKEImage from "../../img/artists/pictures/aKIDcalledMAKE.webp"
import BorgMusicImage from "../../img/artists/pictures/Borg Music.webp"
import BullyMellowImage from "../../img/artists/pictures/Bully Mellow.webp"
import CoppolaImage from "../../img/artists/pictures/Coppola.webp"
import Crypt0m1notaurImage from "../../img/artists/pictures/Crypt0m1notaur.webp"
import DarioLottiImage from "../../img/artists/pictures/Dario Lotti.webp"
import DoD1DoDImage from "../../img/artists/pictures/duo.webp"
import HennyImage from "../../img/artists/pictures/Henny.webp"
import MetaDJImage from "../../img/artists/pictures/Meta DJ.webp"
import MiaMakesMusicImage from "../../img/artists/pictures/MiaMakesMusic.webp"
import MikeRussiImage from "../../img/artists/pictures/Mike Russi.webp"
import NaNaTheApeImage from "../../img/artists/pictures/NaNa The Ape.webp"
import OfficeDrummerImage from "../../img/artists/pictures/OfficeDrummer.webp"
import OhhClaireImage from "../../img/artists/pictures/OhhClaire.webp"
import SarahCoponatImage from "../../img/artists/pictures/Sarah Coponat.webp"
import SteveSaiImage from "../../img/artists/pictures/Steve Sai.webp"
import StoneyEyeImage from "../../img/artists/pictures/Stoney Eye.webp"
import ThugShellsImage from "../../img/artists/pictures/Thug Shells.webp"
import VlouueImage from "../../img/artists/pictures/Vlouue.webp"
import YangMusicImage from "../../img/artists/pictures/YangMusic.webp"
// INSTALLATIONS
// import PsychedelicsAnonymousImage from "../../img/installations/anonymous.webp"
import BosqueGraciasImage from "../../img/installations/bosque-tower.webp"
// import BIIMOImage from "../../img/installations/phygital-gate.webp"
// import MicahAlhadeffImage from "../../img/installations/crystal-cortex.webp"
// import StomImage from "../../img/installations/elevation.webp"
import HapeImage from "../../img/installations/hape.webp"
// import SalawakiImage from "../../img/installations/isthisreal.webp"
// import aKIDcalledBEASTImage from "../../img/installations/kid.webp"
import MusicaW3Image from "../../img/installations/musicaw3.webp"
import NewtroArtsImage from "../../img/installations/newtro.webp"
// import PepeGawdImage from "../../img/installations/parkour.webp"
// import AlanHowickImage from "../../img/installations/pennies.webp"
// import PsychofuturistImage from "../../img/installations/psyhce.webp"
import RadTVImage from "../../img/installations/rad.webp"

interface Artist {
  name: string
  bio: string
  image?: string | null
  socials: {
    twitter?: string | null
    instagram?: string | null
    twitch?: string | null
    website?: string | null
  }
}

interface ScheduleEvent {
  id: number
  title: string
  subtitle?: string
  type?: "X Space" | "Workshop" | "Tour" | "Party"
  stage: string
  startTime: string
  endTime: string
  timeSlotStart: number
  timeSlotEnd: number
  duration: number
  startTimePST: string
  endTimePST: string
  startTimeCET: string
  endTimeCET: string
  startTimeBA: string
  endTimeBA: string
  startTimeEST: string | null
  endTimeEST: string | null
  hasWearable: boolean
  artist?: Artist
}

interface StageSchedule {
  [stageName: string]: ScheduleEvent[]
}

interface DaySchedule {
  [key: string]: StageSchedule
}

const Artists: Record<string, Artist> = {
  "Dario Lotti & Sandro Sax": {
    name: "Dario Lotti & Sandro Sax",
    bio: "Dario Lotti started his career as a DJ way back in 1982. His main genre is house music, a love that has accompanied him for many, many years. His name is directly linked to one of Italy's cult venues, Guendalina in Lecce, which hosts the best international DJs every summer. Everyone at Guendalina is captivated by the wonderful natural setting: a true open-air arena with breathtaking acoustics.\n\nDario has had the opportunity to play alongside names of the calibre of Luciano, Loco Dice, Ritchie Hawtin, Carl Cox, Marco Carola, Little Louie Vega, Deep Dish, T. Humphries, D. Morales, F. Knuckles, Satoshi Tomie, R. Sanchez, E. Morillo, Hector Romero, Tedd Patterson, Kenny Carpenter, Ricky Morrison, Paul Trouble Anderson, Seamus Haji, Xpress 2, Steve Lawler, Nic Fanciulli, Dj Ralf, etc.\n\nDario Lotti boasts numerous appearances as a special guest in foreign cult clubs such as, in the United States: Velvet (San Diego), Motor Lounge (Detroit), Club 128 (Toledo), Nikki Beach (Miami), Club 320 (Miami), Sagamore (Miami), Elevations (Miami). In Switzerland, Dario has played at Q Club/Station Club (Zurich), Diams Club (Sion), D!Club (Lausanne), Mad Club (Lausanne), while in Spain he played at Tito's.\n\nHe also has collaborations with the best Italian clubs/organizations, including: Plastic/Amnesia/Just Cavalli (Milan), Nobody's Perfect@Tenax (Florence), Prince, Pascià, Matis, Kinki, Chalet delle Rose, Angels of Love, Divinae Follie, etc.\n\nBesides being a DJ, Dario Lotti is also a producer and boasts releases on vinyl and compilations from 1993 to the present day. His prominent labels include: Junior Boy's Own, Strictly Rhythm, Defected.",
    socials: {
      twitter: "https://x.com/PiZzArteItaly",
      instagram: "https://www.instagram.com/dariolottidj/",
      twitch: null,
      website: null,
    },
    image: DarioLottiImage,
  },
  Coppola: {
    name: "Coppola",
    bio: "Coppolas journey into electronic music began at just 12 years old, experimenting with Virtual DJ and inspired by a neighbor's\nCDo 1005. By 13, he had acquired his tinst Do controller, and a year later, he ventured into music production.\nAt 15, his talent caught the attention of the Plus talent agency, and by 16, after becoming legally emancipated, h e made his\ndebut a t s\u00e3o Paulo's iconic D-edge, marking the official start of his career. A key collaboration with Gui Boratto further refined\nhis artistry.\nAt 19, Coppola gained national recognition with his track Kings and Queens, leading to performances at Brazil's top clubs and\nfestivals. Always seeking to push creative boundaries, he expanded internationally, captivating audiences in New York,\nBarcelona, and beyond. His work has been embraced by major artists and labels,resulting in releases on prestigious\nplatforms like Diynamic Music, Kompakt Records, Tomorrowland Music, and DOC Records.\nWith an upcoming release on Black Book Records and collaborations alongside Mochakk, Vintage Culture, Rafael Cerato,\nShermanology, Gui Boratto, and Meca, Coppola's future is filled with potential chart-toppers.\nNow 24, Coppola is a rising star in Brazilian electronic music, making waves on the global stage",
    socials: {
      twitter: null,
      instagram: "https://instagram.com/coppoladj",
      twitch: null,
      website: null,
    },
    image: CoppolaImage,
  },
  Henny: {
    name: "Henny",
    bio: "Henny is a self-taught bedroom DJ who takes pride in pressing buttons & turning knobs. With over 10 years of experience as a studio dancer, she's performed in competitions and exhibitions, connecting with dancers from all walks of life. Her dream is to one day open her own dance studio in her hometown, catered towards the lower to middle class demographic. Henny's love for music & community has naturally evolved into her DJ career, where she continues to share her passion and spread the craft. You can find her DJing in the internet realm via Twitch or at various Decentraland venues!",
    socials: {
      twitter: "https://x.com/hennywubs",
      instagram: "https://instagram.com/hennywubs",
      twitch: "https://www.twitch.tv/henny",
      website: null,
    },
    image: HennyImage,
  },
  Vlouue: {
    name: "Vlouue",
    bio: "Vlouue is a Canadian DJ (online and IRL) from Montreal. Over the years she has performed festivals and nightclubs but her residency is on Twitch. She plays various EDM genres but her specialty is Techno and Hard Techno. No matter the techno sub genre from dark and melodic to acid and heavy, she will guide you trough a journey in your darkside.",
    socials: {
      twitter: null,
      instagram: "https://instagram.com/Vlouue",
      twitch: "https://www.twitch.tv/vlouue",
      website: null,
    },
    image: VlouueImage,
  },
  "Borg Music": {
    name: "Borg Music",
    bio: "Borg Music is a creator team based in Japan. Borg Music’s tracks have charted globally, reaching #7 in Canada, #14 in Japan, and #28 in Kyrgyzstan. Borg Music is honored to perform at the Decentraland Music Festival 2025 and looks forward to sharing the joy of music and dance with all the amazing people in this wonderful community!",
    socials: {
      twitter: "https://x.com/borg169",
      instagram: null,
      twitch: null,
      website: null,
    },
    image: BorgMusicImage,
  },
  MEMBA: {
    name: "MEMBA",
    bio: "Will decide on Nov 15",
    socials: {
      twitter: null,
      instagram: null,
      twitch: null,
      website: null,
    },
    image: null,
  },
  "Mike Russi": {
    name: "Mike Russi",
    bio: "Mike Russi started his career as a house DJ in 1999, and went on to become a producer. He is currently busy with his new project, Moolycash",
    socials: {
      twitter: "https://x.com/PiZzArteItaly",
      instagram: null,
      twitch: null,
      website: "https://www.facebook.com/djmaik2",
    },
    image: MikeRussiImage,
  },
  "Sarah Coponat": {
    name: "Sarah Coponat",
    bio: "French pianist, composer, and renowned improviser Sarah Coponat transforms emotion into sound. She creates soul-grasping music through a fusion of classical piano and electronic elements. Her ethereal vocals seem to come from beyond, building complex soundscapes. Sarah’s improvisation sessions are broadcast weekly on Twitch from the CoponatRecordsStudio. She has captivated audiences worldwide, performing in some of the world’s most prestigious venues. Her latest piano album PARIS, premiered at the renowned Salle Cortot - Paris, reaffirming her status as a unique and powerful voice in modern neoclassical music.",
    socials: {
      twitter: "https://x.com/SarahCoponat",
      instagram: "https://www.instagram.com/sarahcoponat",
      twitch: "https://www.twitch.tv/sarahcoponat/about",
      website: "youtube  https://www.youtube.com/sarahcoponat",
    },
    image: SarahCoponatImage,
  },
  OhhClaire: {
    name: "OhhClaire",
    bio: "Claire, a talented German-British DJ and producer, has made a significant impact on the techno music scene in the past years. Currently based in Brunswick, Germany, she quickly gained prominence during the Covid pandemic as one of the most prominent Techno Streamers (also known as OhhClaire) on Twitch. In an astonishingly short span of just one year, Claire captivated audiences worldwide with her unique sound, blending dark and progressive elements with innovative techno influences.",
    socials: {
      twitter: null,
      instagram: "https://www.instagram.com/ohhclaire_/",
      twitch: "https://www.twitch.tv/ohhclaire",
      website: "https://linktr.ee/ohhclaire",
    },
    image: OhhClaireImage,
  },
  "Bully Meow": {
    name: "Bully Meow",
    bio: "Bully Meow brings high-energy live guitar and vocals to stages from the metaverse to the real world. A native Web3 performer since 2020, Bully played 56 live shows on TokenSmart during the 2021-22 bull run, blending rock, blues, metal, Latin, and downtempo into an electrifying mix. With 11 Music NFT collections and 2,000+ collectors, Bully bridges digital and live performance culture like few others. Fans may also hold one of 1,800 rare TokenSmart POAPs celebrating his shows. Expect soulful slide guitar, soaring hooks, and a truly interactive experience every time Bully Meow plugs in and turns it up.",
    socials: {
      twitter: "https://twitter.com/bullymeow",
      instagram: "https://instagram.com/bullymeowmusic",
      twitch: null,
      website: "https://bullymeow.com",
    },
    image: BullyMellowImage,
  },
  "Stoney Eye": {
    name: "Stoney Eye",
    bio: "Stoney Eye is a live dub remixer, DJ, and multi-instrumentalist blending reggae, hip-hop, and electronic beats into immersive performances. Known across Decentraland for MoFyah Monday, one of the metaverse’s longest-running residencies, Stoney Eye brings a fresh, high-energy vibe to every set. As a collaborative force, he’s a key member of the MetaTribe and House of Yeba communities, creating a space where culture and beats collide. For DCLMF25, expect deep basslines, live instrumentation, and the signature Stoney Eye sound that moves the crowd.",
    socials: {
      twitter: "https://x.com/stoneyeye",
      instagram: "https://instagram.com/stoneyeye",
      twitch: null,
      website: "https://stoneyeye.com/",
    },
    image: StoneyEyeImage,
  },
  "DJ aKIDcalledMAKE": {
    name: "DJ aKIDcalledMAKE",
    bio: "aKIDcalledMAKE is the founder of the aKIDcalledBEAST project, a 3D digital collectible at the intersection of art, culture, fashion, and music. aKIDcalledBEAST is a unique AR-enabled 3D avatar for the metaverse, VR, and gaming environments. MAKE, a web3 builder for the last four years, also has a background in music as a DJ/producer for over 15 years. Having played in clubs across Europe and Canada, as well as multiple metaverse music festivals, he is well-versed in the electronic dance music scene.",
    socials: {
      twitter: "https://x.com/makeanft",
      instagram: "https://instagram.com/makeanft",
      twitch: "https://www.twitch.tv/makeanft",
      website: null,
    },
    image: aKIDcalledMAKEImage,
  },
  YangMusic: {
    name: "YangMusic",
    bio: "Yang is a multi-instrumentalist producer who blends jazz, R&B, and soul with electronic elements to create a unique Lo-Fi sound. Since starting his journey in Decentraland in late 2021, Yang has performed at major metaverse events like Metaverse Fashion Week and Art Week, while also hosting a weekly residency at the Stronghold. A familiar name in the Web3 music scene, Yang is also part of the duo 'Butter' with Kornél Kovács. At DCLMF25, he’ll be showcasing his new live set—bringing fresh beats and soulful vibes to the virtual stage.",
    socials: {
      twitter: "https://x.com/yangmusic7",
      instagram: "https://instagram.com/yangmusic7",
      twitch: null,
      website: "https://distrokid.com/hyperfollow/yang5/dclmf-2023-mix",
    },
    image: YangMusicImage,
  },
  "Thug Shells": {
    name: "Thug Shells",
    bio: "When Thug Shells hops on the decks, expect freestyle rap fuego mixed with banging beats! Known for her infectious positivity and gangster adorability, prepare for a set full of bass, bars, and big smiles - you're definitely gonna join the cult after you hear her throw down on the digital dancefloor!",
    socials: {
      twitter: "https://x.com/thugshells",
      instagram: "https://www.instagram.com/thugshells",
      twitch: "https://www.twitch.tv/thugshells",
      website: null,
    },
    image: ThugShellsImage,
  },
  MiaMakesMusic: {
    name: "MiaMakesMusic",
    bio: "Mia is an indie-pop artist who plays the piano and ukulele. She has been creating content for over 10 years, starting on YouTube and eventually moving to Twitch where she has built an amazing community. Mia's goal is to create a safe, comfy, and cozy space for everyone who stops by her streams and to help put a smile on people's faces. She hopes to make people happy with her music!",
    socials: {
      twitter: "https://x.com/miamakesmusic",
      instagram: "https://instagram.com/miamakesmusic",
      twitch: "https://www.twitch.tv/miamakesmusic",
      website: "https://miamakesmusic.com",
    },
    image: MiaMakesMusicImage,
  },
  OfficeDrummer: {
    name: "OfficeDrummer",
    bio: "OfficeDrummer is a twitch sensation, playing drums all over the world & having multiple high level collaborations. He is known for his high energy and positivity, along with a knack for degeneracy,",
    socials: {
      twitter: "https://x.com/officedrummer",
      instagram: "https://instagram.com/officedrummer",
      twitch: "https://www.twitch.tv/officedrummer",
      website: null,
    },
    image: OfficeDrummerImage,
  },
  MetaDJ: {
    name: "MetaDJ",
    bio: "MetaDJ is a decentralized community of music enthusiasts, performers, and visual artists dedicated to bringing live music events to the Metaverse. Since its inception in 2021, MetaDJ has empowered up-and-coming artists by providing them with a platform to showcase their talent in the virtual world. With a focus on diverse genres and interactive experiences, MetaDJ is redefining how we experience live music in the digital age.",
    socials: {
      twitter: "https://x.com/MetaDJ_DCL",
      instagram: null,
      twitch: null,
      website: null,
    },
    image: MetaDJImage,
  },
  Crypt0m1notaur: {
    name: "Crypt0m1notaur",
    bio: "Beast hood DJ / 3D Artist",
    socials: {
      twitter: "https://x.com/Crypt0m1notaur",
      instagram: null,
      twitch: null,
      website: null,
    },
    image: Crypt0m1notaurImage,
  },
  "Dúo Dø": {
    name: "Dúo Dø",
    bio: "Formed in late 2023 in Buenos Aires, Dúo Dø is an electronic music project blending Deep, Tech, Melodic, and Progressive House with Organic House and Ethnic Deep/Afro influences. Composed of J.W. (Julián Waisbord, DJ) and C.M. (Carlos Munuce, electric bass), the duo creates immersive soundscapes by merging DJing with live instrumental improvisation. J.W. sets the rhythmic and atmospheric foundation, while C.M. adds groove and texture with live basslines, bringing a unique, dynamic energy to their sets.",
    socials: {
      twitter: "https://x.com/duododcl",
      instagram: "https://instagram.com/duododcl",
      twitch: null,
      website: null,
    },
    image: DoD1DoDImage,
  },
  "NaNa The Ape": {
    name: "NaNa The Ape",
    bio: "NaNa the Ape is a multi-talented virtual artist, singer-songwriter, and DJ, known for her deep, soulful vocals and genre-blending sound that fuses R&B, Afrobeats, and EDM. As a prominent figure in the metaverse music scene, she has performed at major virtual festivals, bringing an electrifying energy to every set. With a passion for pushing creative boundaries, NaNa continues to captivate global audiences, bridging the gap between digital culture and live performance.",
    socials: {
      twitter: "https://x.com/nanatheape",
      instagram: "https://instagram.com/nanatheape",
      twitch: null,
      website: null,
    },
    image: NaNaTheApeImage,
  },
  "Steve Sai": {
    name: "Steve Sai",
    bio: "Steve Sai is a pioneering electronic music artist and DJ with a career spanning over two decades. Known for his deep, hypnotic techno soundscapes and intricate melodic layers, he has been a key figure in the underground music scene. With releases on top-tier labels and performances at major festivals and clubs, Steve Sai masterfully blends analog warmth with digital precision. Constantly evolving, he continues to push the boundaries of electronic music, delivering immersive sonic experiences that resonate on both physical and virtual dancefloors.",
    socials: {
      twitter: "https://x.com/stevesai_music",
      instagram: "https://instagram.com/steve_sai_official",
      twitch: null,
      website: "https://stevesai.com",
    },
    image: SteveSaiImage,
  },
  "Bosque Gracias": {
    name: "Bosque Gracias",
    bio: "BosqueGracias is an artistic community from Patagonia exploring the intersection of nature, art, and tech through immersive web3 experiences and IRL art residencies. For over ten years, they have integrated traditional crafts (like textiles and natural dyes) with digital tools and blockchain technology, emphasizing sustainability and the repurposing of obsolete tech in their collaborative processes. Their venue, the Bosque Tower, will host live meditations and DJ sessions, bringing cross-disciplinary dialogue between the forest and the digital world. Featured artists include NikoAlerce, Glitchrama, and Roc\u00edo Mio, who share insights from their Patagonian residencies.",
    image: BosqueGraciasImage,
    socials: {
      twitter: "https://x.com/BosqueGracias",
      instagram: "https://instagram.com/bosquegracias",
      twitch: null,
      website: null,
    },
  },
  "Rad.Live": {
    name: "Rad TV",
    bio: "Rad TV's Live Feed is a three-day, open-genre music video showcase built for creators that want to connect with other artists and their fans! From December 3rd-5th, artists from around the world will stream their creations from Rad TV into Decentraland, turning Rad TV's Party Pad into a personal stage for discovery, connection, and live creative energy. Upload your videos at RadTV.com and submit them here.",
    image: RadTVImage,
    socials: {
      twitter: "https://x.com/RadNFTV",
      instagram: "https://instagram.com/radnftv",
      twitch: null,
      website: null,
    },
  },
  Hape: {
    name: "Hape",
    bio: "Hape is a global digital fashion IP innovating in Web3 by merging fashion, culture, and technology to create unique experiences. Partnered with brands like Diesel and Jägermeister, Hape continues to bridge digital and physical worlds. Returning to Decentraland this time, Hape brings its signature digital lifestyle with an immersive showcase of fashion and music. From the DJ booth and panel to coin scavenger hunt, every activation celebrates creativity, collaboration, and community spirit, featuring exclusive Wearables, hidden rewards, and the bold energy that defines Hape.",
    image: HapeImage,
    socials: {
      twitter: "https://x.com/HAPEsocial",
      instagram: "https://instagram.com/hapesocial",
      twitch: null,
      website: "https://hape.io/",
    },
  },
  MusicaW3: {
    name: "MusicaW3",
    bio: "MusicaW3 is a music festival in the metaverse. It is a place where artists can showcase their music and connect with other artists and fans.",
    image: MusicaW3Image,
    socials: {
      twitter: "https://x.com/MusicaW3",
      instagram: "https://instagram.com/musicaw3",
    },
  },
  "Newtro Arts": {
    name: "Newtro Arts",
    bio: "Newtro Arts is a music festival in the metaverse. It is a place where artists can showcase their music and connect with other artists and fans.",
    image: NewtroArtsImage,
    socials: {
      twitter: "https://x.com/NewtroArts",
      instagram: "https://instagram.com/newtroarts",
    },
  },
}

// Helper function to convert UTC time to PST (UTC - 7 hours)
const convertToPST = (utcTime: string): string => {
  if (utcTime === "Midday") return "05:00"
  if (utcTime === "Midnight") return "17:00"

  const hour = parseInt(utcTime.split(":")[0])
  let pstHour = hour - 7

  // Handle day boundary crossing
  if (pstHour < 0) {
    pstHour += 24
  }

  // Format with leading zero if needed
  const formattedHour = pstHour.toString().padStart(2, "0")
  return `${formattedHour}:00`
}

const timeSlots: string[] = [
  "10:00",
  "11:00",
  "Midday",
  "13:00",
  "14:00",
  "15:00",
  "16:00",
  "17:00",
  "18:00",
  "19:00",
  "20:00",
  "21:00",
  "22:00",
  "23:00",
  "Midnight",
  "01:00",
  "02:00",
  "03:00",
  "04:00",
  "05:00",
  "06:00",
  "07:00",
  "08:00",
  "09:00",
]

const stages = ["Main Stage"] as const

const scheduleData: DaySchedule = {
  "dec-3": {
    "Main Stage": [
      {
        id: 1,
        title: "Music Meditation",
        subtitle: "BosqueGracias guided meditation with LoFi Andino",
        type: "Workshop",
        stage: "Bosque Tower",
        startTime: "Midday",
        endTime: "13:00",
        timeSlotStart: 2,
        timeSlotEnd: 2,
        duration: 1,
        startTimePST: "05:00",
        endTimePST: "06:00",
        startTimeCET: "01:00pm",
        endTimeCET: "14:00",
        startTimeBA: "09:00am",
        endTimeBA: "10:00",
        startTimeEST: "07.00am",
        endTimeEST: null,
        artist: Artists["Bosque Gracias"],
        hasWearable: false,
      },
      {
        id: 2,
        title: "Rad TV Live Feed",
        subtitle: "Music videos from the Rad TV community",
        stage: "RAD Party Pad",
        startTime: "13:00",
        endTime: "14:00",
        timeSlotStart: 3,
        timeSlotEnd: 3,
        duration: 1,
        startTimePST: "06:00",
        endTimePST: "07:00",
        startTimeCET: "02:00pm",
        endTimeCET: "15:00",
        startTimeBA: "10:00am",
        endTimeBA: "11:00",
        startTimeEST: "08:00am",
        endTimeEST: "09:00",
        hasWearable: false,
        artist: Artists["Rad.Live"],
      },
      {
        id: 3,
        title: "Hape Party",
        subtitle: "DJs at the Hape Party Pad",
        stage: "Hape Party Pad",
        startTime: "14:00",
        endTime: "16:00",
        timeSlotStart: 4,
        timeSlotEnd: 4,
        duration: 2,
        startTimePST: "07:00",
        endTimePST: "08:00",
        startTimeCET: "03:00pm",
        endTimeCET: "16:00",
        startTimeBA: "11:00am",
        endTimeBA: "12:00",
        startTimeEST: "09:00am",
        endTimeEST: "10:00",
        hasWearable: false,
        artist: Artists["Hape"],
      },
      {
        id: 4,
        title: "Pure House Sax Live @ The Bunker",
        subtitle: "Dario Lotti & Sandro Sax live at The Bunker (-94,83)",
        stage: "The Bunker",
        startTime: "16:00",
        endTime: "18:00",
        timeSlotStart: 6,
        timeSlotEnd: 6,
        duration: 2,
        startTimePST: "09:00",
        endTimePST: "10:00",
        startTimeCET: "05:00pm",
        endTimeCET: "18:00",
        startTimeBA: "01:00pm",
        endTimeBA: "14:00",
        startTimeEST: "11:00am",
        endTimeEST: "12:00",
        hasWearable: false,
        artist: Artists["Dario Lotti & Sandro Sax"],
      },
      {
        id: 5,
        title: "MusicaW3 Live Session",
        subtitle: "Live sessions at the MusicaW3 Party Pad",
        stage: "MusicaW3 Party Pad",
        startTime: "18:00",
        endTime: "20:00",
        timeSlotStart: 8,
        timeSlotEnd: 8,
        duration: 2,
        startTimePST: "11:00",
        endTimePST: "12:00",
        startTimeCET: "07:00pm",
        endTimeCET: "20:00",
        startTimeBA: "03:00pm",
        endTimeBA: "16:00",
        startTimeEST: "01:00pm",
        endTimeEST: "14:00",
        hasWearable: false,
        artist: Artists["MusicaW3"],
      },
      {
        id: 6,
        title: "Live Tour",
        subtitle: "Festival tour with Psychofuturist & Alan Howick",
        stage: "Live Stage",
        startTime: "20:00",
        endTime: "21:00",
        timeSlotStart: 10,
        timeSlotEnd: 10,
        duration: 1,
        startTimePST: "13:00",
        endTimePST: "14:00",
        startTimeCET: "09:00pm",
        endTimeCET: "22:00",
        startTimeBA: "05:00pm",
        endTimeBA: "18:00",
        startTimeEST: "03:00pm",
        endTimeEST: "16:00",
        hasWearable: false,
      },
      {
        id: 7,
        title: "Coppola",
        subtitle: "Main Stage set with merch",
        stage: "Main Stage",
        startTime: "21:00",
        endTime: "22:00",
        timeSlotStart: 11,
        timeSlotEnd: 11,
        duration: 1,
        startTimePST: "14:00",
        endTimePST: "15:00",
        startTimeCET: "10:00pm",
        endTimeCET: "23:00",
        startTimeBA: "06:00pm",
        endTimeBA: "19:00",
        startTimeEST: "04:00pm",
        endTimeEST: "17:00",
        hasWearable: true,
        artist: Artists["Coppola"],
      },
      {
        id: 8,
        title: "Henny",
        subtitle: "Main Stage set",
        stage: "Main Stage",
        startTime: "22:00",
        endTime: "23:00",
        timeSlotStart: 12,
        timeSlotEnd: 12,
        duration: 1,
        startTimePST: "15:00",
        endTimePST: "16:00",
        startTimeCET: "11:00pm",
        endTimeCET: "00:00",
        startTimeBA: "07:00pm",
        endTimeBA: "20:00",
        startTimeEST: "05:00pm",
        endTimeEST: "18:00",
        hasWearable: false,
        artist: Artists["Henny"],
      },
      {
        id: 9,
        title: "Vlouue",
        subtitle: "Main Stage set with merch",
        stage: "Main Stage",
        startTime: "23:00",
        endTime: "Midnight",
        timeSlotStart: 13,
        timeSlotEnd: 13,
        duration: 1,
        startTimePST: "16:00",
        endTimePST: "17:00",
        startTimeCET: "Midnight",
        endTimeCET: "01:00",
        startTimeBA: "08:00pm",
        endTimeBA: "21:00",
        startTimeEST: "06:00pm",
        endTimeEST: "19:00",
        hasWearable: true,
        artist: Artists["Vlouue"],
      },
      {
        id: 10,
        title: "Borg Music",
        subtitle: "Main Stage set",
        stage: "Main Stage",
        startTime: "Midnight",
        endTime: "01:00",
        timeSlotStart: 14,
        timeSlotEnd: 14,
        duration: 1,
        startTimePST: "17:00",
        endTimePST: "18:00",
        startTimeCET: "01:00am",
        endTimeCET: "02:00",
        startTimeBA: "09:00pm",
        endTimeBA: "22:00",
        startTimeEST: "07:00pm",
        endTimeEST: "20:00",
        hasWearable: false,
        artist: Artists["Borg Music"],
      },
      {
        id: 10,
        title: "MEMBA",
        subtitle: "Midnight Diner Presents: MEMBA & Special Guests",
        stage: "Main Stage",
        startTime: "01:00",
        endTime: "02:00",
        timeSlotStart: 15,
        timeSlotEnd: 15,
        duration: 1,
        startTimePST: "17:00",
        endTimePST: "18:00",
        startTimeCET: "01:00am",
        endTimeCET: "02:00",
        startTimeBA: "09:00pm",
        endTimeBA: "22:00",
        startTimeEST: "07:00pm",
        endTimeEST: "20:00",
        hasWearable: false,
      },
      {
        id: 10,
        title: "BosqueGracias Live Set",
        subtitle: "Live music by Glitchrama, RocioMio & NikoAlerce",
        stage: "Bosque Tower",
        startTime: "02:00",
        endTime: "03:00",
        timeSlotStart: 16,
        timeSlotEnd: 16,
        duration: 1,
        startTimePST: "17:00",
        endTimePST: "18:00",
        startTimeCET: "01:00am",
        endTimeCET: "02:00",
        startTimeBA: "09:00pm",
        endTimeBA: "22:00",
        startTimeEST: "07:00pm",
        endTimeEST: "20:00",
        hasWearable: false,
        artist: Artists["Bosque Gracias"],
      },
      {
        id: 10,
        title: "Newtro Live Session",
        subtitle: "Live sessions at the Newtro Arts Party Pad",
        stage: "Newtro Arts Party Pad",
        startTime: "03:00",
        endTime: "05:00",
        timeSlotStart: 17,
        timeSlotEnd: 17,
        duration: 2,
        startTimePST: "17:00",
        endTimePST: "18:00",
        startTimeCET: "01:00am",
        endTimeCET: "02:00",
        startTimeBA: "09:00pm",
        endTimeBA: "22:00",
        startTimeEST: "07:00pm",
        endTimeEST: "20:00",
        hasWearable: false,
        artist: Artists["Newtro Arts"],
      },
      {
        id: 10,
        title: "Meta Tribe Afterparty",
        subtitle: "MetaDJ live at Meta Tribe Plaza (109,50)",
        stage: "Meta Tribe Plaza",
        startTime: "05:00",
        endTime: "07:00",
        timeSlotStart: 19,
        timeSlotEnd: 20,
        duration: 2,
        startTimePST: "17:00",
        endTimePST: "18:00",
        startTimeCET: "01:00am",
        endTimeCET: "02:00",
        startTimeBA: "09:00pm",
        endTimeBA: "22:00",
        startTimeEST: "07:00pm",
        endTimeEST: "20:00",
        hasWearable: false,
      },
      {
        id: 10,
        title: "Interval",
        subtitle: "Hunt the 19 gifts hidden in the Music Festival Plaza",
        stage: "Gift Shop",
        startTime: "07:00",
        endTime: "11:00",
        timeSlotStart: 21,
        timeSlotEnd: 22,
        duration: 3,
        startTimePST: "17:00",
        endTimePST: "18:00",
        startTimeCET: "01:00am",
        endTimeCET: "02:00",
        startTimeBA: "09:00pm",
        endTimeBA: "22:00",
        startTimeEST: "07:00pm",
        endTimeEST: "20:00",
        hasWearable: false,
      },
    ],
  },
  "dec-4": {
    "Main Stage": [
      {
        id: 1222,
        title: "Interval",
        subtitle: "Hunt the 19 gifts hidden in the Music Festival Plaza",
        stage: "Gift Shop",
        startTime: "07:00",
        endTime: "11:00",
        timeSlotStart: 0,
        timeSlotEnd: 0,
        duration: 1,
        startTimePST: "04:00",
        endTimePST: "05:00",
        startTimeCET: "12:00am",
        endTimeCET: "01:00",
        startTimeBA: "08:00am",
        endTimeBA: "09:00",
        startTimeEST: "06:00am",
        endTimeEST: "07:00",
        hasWearable: false,
      },
      {
        id: 12,
        title: "Retro Partea Pad",
        subtitle: "Facemoon Gallery warmup with DJ Abillitea (-117,71)",
        stage: "Facemoon Gallery",
        startTime: "11:00",
        endTime: "Midday",
        timeSlotStart: 1,
        timeSlotEnd: 1,
        duration: 1,
        startTimePST: "04:00",
        endTimePST: "05:00",
        startTimeCET: "12:00am",
        endTimeCET: "01:00",
        startTimeBA: "08:00am",
        endTimeBA: "09:00",
        startTimeEST: "06:00am",
        endTimeEST: "07:00",
        hasWearable: false,
      },
      {
        id: 12,
        title: "Interval",
        subtitle: "Hunt the 19 gifts hidden in the Music Festival Plaza",
        stage: "Gift Shop",
        startTime: "Midday",
        endTime: "13:00",
        timeSlotStart: 2,
        timeSlotEnd: 2,
        duration: 1,
        startTimePST: "04:00",
        endTimePST: "05:00",
        startTimeCET: "12:00am",
        endTimeCET: "01:00",
        startTimeBA: "08:00am",
        endTimeBA: "09:00",
        startTimeEST: "06:00am",
        endTimeEST: "07:00",
        hasWearable: false,
      },
      {
        id: 13,
        title: "BosqueGracias Art Residency",
        subtitle: "Rocío Mio talks artist residencies in Argentine Patagonia",
        stage: "Bosque Tower",
        startTime: "13:00",
        endTime: "14:00",
        timeSlotStart: 3,
        timeSlotEnd: 3,
        duration: 1,
        startTimePST: "06:00",
        endTimePST: "07:00",
        startTimeCET: "02:00pm",
        endTimeCET: "15:00",
        startTimeBA: "10:00am",
        endTimeBA: "11:00",
        startTimeEST: "08:00am",
        endTimeEST: "09:00",
        hasWearable: false,
        artist: Artists["Bosque Gracias"],
      },
      {
        id: 14,
        title: "Hape Party",
        subtitle: "DJs at the Hape Party Pad",
        stage: "Hape Party Pad",
        startTime: "14:00",
        endTime: "16:00",
        timeSlotStart: 4,
        timeSlotEnd: 4,
        duration: 2,
        startTimePST: "07:00",
        endTimePST: "08:00",
        startTimeCET: "03:00pm",
        endTimeCET: "16:00",
        startTimeBA: "11:00am",
        endTimeBA: "12:00",
        startTimeEST: "09:00am",
        endTimeEST: "10:00",
        hasWearable: false,
        artist: Artists["Hape"],
      },
      {
        id: 16,
        title: "Bunker House Set",
        subtitle: "Mike Russi spins 2 hours of house at Bunker (-94,83)",
        stage: "Bunker",
        startTime: "16:00",
        endTime: "18:00",
        timeSlotStart: 6,
        timeSlotEnd: 6,
        duration: 1,
        startTimePST: "09:00",
        endTimePST: "11:00",
        startTimeCET: "05:00pm",
        endTimeCET: "18:00",
        startTimeBA: "01:00pm",
        endTimeBA: "14:00",
        startTimeEST: "11:00am",
        endTimeEST: "12:00",
        hasWearable: false,
        artist: Artists["Mike Russi"],
      },
      {
        id: 17,
        title: "Rad TV Live Feed",
        subtitle: "Music videos from the Rad TV community",
        stage: "Main Stage",
        startTime: "17:00",
        endTime: "18:00",
        timeSlotStart: 7,
        timeSlotEnd: 7,
        duration: 1,
        startTimePST: "10:00",
        endTimePST: "11:00",
        startTimeCET: "06:00pm",
        endTimeCET: "19:00",
        startTimeBA: "02:00pm",
        endTimeBA: "15:00",
        startTimeEST: "Midday",
        endTimeEST: "13:00",
        hasWearable: false,
        artist: Artists["Rad.Live"],
      },
      {
        id: 18,
        title: "MusicaW3 Live Session",
        subtitle: "Live sessions at the MusicaW3 Party Pad",
        stage: "MusicaW3 Party Pad",
        startTime: "18:00",
        endTime: "19:00",
        timeSlotStart: 8,
        timeSlotEnd: 8,
        duration: 2,
        startTimePST: "11:00",
        endTimePST: "12:00",
        startTimeCET: "07:00pm",
        endTimeCET: "20:00",
        startTimeBA: "03:00pm",
        endTimeBA: "16:00",
        startTimeEST: "01:00pm",
        endTimeEST: "14:00",
        hasWearable: false,
        artist: Artists["MusicaW3"],
      },
      {
        id: 20,
        title: "Live Tour",
        subtitle: "Festival tour with Cansy & CarlosMu",
        stage: "Live Stage",
        startTime: "20:00",
        endTime: "21:00",
        timeSlotStart: 10,
        timeSlotEnd: 10,
        duration: 1,
        startTimePST: "13:00",
        endTimePST: "14:00",
        startTimeCET: "09:00pm",
        endTimeCET: "22:00",
        startTimeBA: "05:00pm",
        endTimeBA: "18:00",
        startTimeEST: "03:00pm",
        endTimeEST: "16:00",
        hasWearable: false,
      },
      {
        id: 21,
        title: "Sarah Coponat",
        subtitle: "Main Stage set with merch",
        stage: "Main Stage",
        startTime: "21:00",
        endTime: "22:00",
        timeSlotStart: 11,
        timeSlotEnd: 11,
        duration: 1,
        startTimePST: "14:00",
        endTimePST: "15:00",
        startTimeCET: "10:00pm",
        endTimeCET: "23:00",
        startTimeBA: "06:00pm",
        endTimeBA: "19:00",
        startTimeEST: "04:00pm",
        endTimeEST: "17:00",
        hasWearable: true,
        artist: Artists["Sarah Coponat"],
      },
      {
        id: 22,
        title: "OhhClaire",
        subtitle: "Main Stage set",
        stage: "Main Stage",
        startTime: "22:00",
        endTime: "23:00",
        timeSlotStart: 12,
        timeSlotEnd: 12,
        duration: 1,
        startTimePST: "15:00",
        endTimePST: "16:00",
        startTimeCET: "11:00pm",
        endTimeCET: "00:00",
        startTimeBA: "07:00pm",
        endTimeBA: "20:00",
        startTimeEST: "05:00pm",
        endTimeEST: "18:00",
        hasWearable: false,
        artist: Artists["OhhClaire"],
      },
      {
        id: 23,
        title: "Bully Meow",
        subtitle: "Live Stage set",
        stage: "Live Stage",
        startTime: "23:00",
        endTime: "Midnight",
        timeSlotStart: 13,
        timeSlotEnd: 13,
        duration: 1,
        startTimePST: "16:00",
        endTimePST: "17:00",
        startTimeCET: "Midnight",
        endTimeCET: "01:00",
        startTimeBA: "08:00pm",
        endTimeBA: "21:00",
        startTimeEST: "06:00pm",
        endTimeEST: "19:00",
        hasWearable: false,
        artist: Artists["Bully Meow"],
      },
      {
        id: 24,
        title: "Stoney Eye",
        subtitle: "Live Stage set",
        stage: "Live Stage",
        startTime: "Midnight",
        endTime: "01:00",
        timeSlotStart: 14,
        timeSlotEnd: 14,
        duration: 1,
        startTimePST: "17:00",
        endTimePST: "18:00",
        startTimeCET: "01:00am",
        endTimeCET: "02:00",
        startTimeBA: "09:00pm",
        endTimeBA: "22:00",
        startTimeEST: "07:00pm",
        endTimeEST: "20:00",
        hasWearable: false,
        artist: Artists["Stoney Eye"],
      },
      {
        id: 25,
        title: "aKidCalledMake",
        subtitle: "Main Stage set with merch",
        stage: "Main Stage",
        startTime: "01:00",
        endTime: "02:00",
        timeSlotStart: 15,
        timeSlotEnd: 15,
        duration: 1,
        startTimePST: "18:00",
        endTimePST: "19:00",
        startTimeCET: "02:00am",
        endTimeCET: "03:00",
        startTimeBA: "10:00pm",
        endTimeBA: "23:00",
        startTimeEST: "08:00pm",
        endTimeEST: "21:00",
        hasWearable: true,
        artist: Artists["DJ aKIDcalledMAKE"],
      },
      {
        id: 26,
        title: "aKIDcalledBEAST Party ",
        subtitle: "DJ Fity & Nateguppy from the AKCB Community",
        stage: "aKidcalledBeast Party Pad",
        startTime: "02:00",
        endTime: "04:00",
        timeSlotStart: 16,
        timeSlotEnd: 16,
        duration: 2,
        startTimePST: "19:00",
        endTimePST: "20:00",
        startTimeCET: "03:00am",
        endTimeCET: "04:00",
        startTimeBA: "11:00pm",
        endTimeBA: "00:00",
        startTimeEST: "09:00pm",
        endTimeEST: "22:00",
        hasWearable: false,
        artist: Artists["aKIDcalledBEAST"],
      },
      {
        id: 26,
        title: "Newtro Live ",
        subtitle: "Live sessions at the Newtro Arts Party Pad",
        stage: "Newtro Arts Party Pad",
        startTime: "04:00",
        endTime: "06:00",
        timeSlotStart: 18,
        timeSlotEnd: 18,
        duration: 2,
        startTimePST: "19:00",
        endTimePST: "20:00",
        startTimeCET: "03:00am",
        endTimeCET: "04:00",
        startTimeBA: "11:00pm",
        endTimeBA: "00:00",
        startTimeEST: "09:00pm",
        endTimeEST: "22:00",
        hasWearable: false,
        artist: Artists["Newtro Arts"],
      },
      {
        id: 28,
        title: "Meta Tribe Afterparty",
        subtitle: "Austin De Chêne live at Meta Tribe Plaza (109,50)",
        stage: "Meta Tribe Plaza",
        startTime: "06:00",
        endTime: "08:00",
        timeSlotStart: 20,
        timeSlotEnd: 20,
        duration: 2,
        startTimePST: "19:00",
        endTimePST: "20:00",
        startTimeCET: "03:00am",
        endTimeCET: "04:00",
        startTimeBA: "11:00pm",
        endTimeBA: "00:00",
        startTimeEST: "09:00pm",
        endTimeEST: "22:00",
        hasWearable: false,
      },
      {
        id: 28,
        title: "Interval",
        subtitle: "Hunt the 19 gifts hidden in the Music Festival Plaza",
        stage: "Gift Shop",
        startTime: "08:00",
        endTime: "11:00",
        timeSlotStart: 22,
        timeSlotEnd: 22,
        duration: 2,
        startTimePST: "19:00",
        endTimePST: "20:00",
        startTimeCET: "03:00am",
        endTimeCET: "04:00",
        startTimeBA: "11:00pm",
        endTimeBA: "00:00",
        startTimeEST: "09:00pm",
        endTimeEST: "22:00",
        hasWearable: false,
      },
    ],
  },
  "dec-5": {
    "Main Stage": [
      {
        id: 27,
        title: "Interval",
        subtitle: "Hunt the 19 gifts hidden in the Music Festival Plaza",
        stage: "Gift Shop",
        startTime: "10:00",
        endTime: "11:00",
        timeSlotStart: 0,
        timeSlotEnd: 0,
        duration: 1,
        startTimePST: "04:00",
        endTimePST: "05:00",
        startTimeCET: "12:00am",
        endTimeCET: "01:00",
        startTimeBA: "08:00am",
        endTimeBA: "09:00",
        startTimeEST: "06:00am",
        endTimeEST: "07:00",
        hasWearable: false,
      },
      {
        id: 27,
        title: "Retro Partea Pad",
        subtitle: "Facemoon Gallery warmup with DJ Abillitea (-117,71)",
        stage: "Facemoon Gallery",
        startTime: "11:00",
        endTime: "Midday",
        timeSlotStart: 1,
        timeSlotEnd: 1,
        duration: 1,
        startTimePST: "04:00",
        endTimePST: "05:00",
        startTimeCET: "12:00am",
        endTimeCET: "01:00",
        startTimeBA: "08:00am",
        endTimeBA: "09:00",
        startTimeEST: "06:00am",
        endTimeEST: "07:00",
        hasWearable: false,
      },
      {
        id: 279,
        title: "Interval",
        subtitle: "Hunt the 19 gifts hidden in the Music Festival Plaza",
        stage: "Gift Shop",
        startTime: "Midday",
        endTime: "13:00",
        timeSlotStart: 2,
        timeSlotEnd: 2,
        duration: 1,
        startTimePST: "04:00",
        endTimePST: "05:00",
        startTimeCET: "12:00am",
        endTimeCET: "01:00",
        startTimeBA: "08:00am",
        endTimeBA: "09:00",
        startTimeEST: "06:00am",
        endTimeEST: "07:00",
        hasWearable: false,
      },
      {
        id: 28,
        title: "Live Tour",
        subtitle: "Festival tour with Salawaki & Hape",
        stage: "Live Stage",
        startTime: "13:00",
        endTime: "14:00",
        timeSlotStart: 3,
        timeSlotEnd: 3,
        duration: 1,
        startTimePST: "06:00",
        endTimePST: "07:00",
        startTimeCET: "02:00pm",
        endTimeCET: "15:00",
        startTimeBA: "10:00am",
        endTimeBA: "11:00",
        startTimeEST: "08:00am",
        endTimeEST: "09:00",
        hasWearable: false,
      },
      {
        id: 29,
        title: "YangMusic",
        subtitle: "Main Stage set",
        stage: "Main Stage",
        startTime: "14:00",
        endTime: "15:00",
        timeSlotStart: 4,
        timeSlotEnd: 4,
        duration: 1,
        startTimePST: "07:00",
        endTimePST: "08:00",
        startTimeCET: "03:00pm",
        endTimeCET: "16:00",
        startTimeBA: "11:00am",
        endTimeBA: "12:00",
        startTimeEST: "09:00am",
        endTimeEST: "10:00",
        hasWearable: false,
        artist: Artists["YangMusic"],
      },
      {
        id: 30,
        title: "Rad TV Live Feed",
        subtitle: "Music videos from the Rad TV community",
        stage: "Rad TV Party Pad",
        startTime: "15:00",
        endTime: "16:00",
        timeSlotStart: 5,
        timeSlotEnd: 5,
        duration: 1,
        startTimePST: "08:00",
        endTimePST: "09:00",
        startTimeCET: "04:00pm",
        endTimeCET: "17:00",
        startTimeBA: "12:00pm",
        endTimeBA: "13:00",
        startTimeEST: "10:00am",
        endTimeEST: "11:00",
        hasWearable: false,
        artist: Artists["Rad.Live"],
      },
      {
        id: 31,
        title: "Hape Party",
        subtitle: "DJs at the Hape Party Pad",
        stage: "Hape Party Pad",
        startTime: "16:00",
        endTime: "18:00",
        timeSlotStart: 6,
        timeSlotEnd: 6,
        duration: 2,
        startTimePST: "09:00",
        endTimePST: "10:00",
        startTimeCET: "05:00pm",
        endTimeCET: "18:00",
        startTimeBA: "01:00pm",
        endTimeBA: "14:00",
        startTimeEST: "11:00am",
        endTimeEST: "12:00",
        hasWearable: false,
        artist: Artists["Hape"],
      },
      {
        id: 33,
        title: "MusicaW3 Party Session",
        subtitle: "DJ Lebanjy at the MusicaW3 Party Pad",
        stage: "MusicaW3 Party Pad",
        startTime: "18:00",
        endTime: "21:00",
        timeSlotStart: 8,
        timeSlotEnd: 8,
        duration: 3,
        startTimePST: "11:00",
        endTimePST: "12:00",
        startTimeCET: "07:00pm",
        endTimeCET: "20:00",
        startTimeBA: "03:00pm",
        endTimeBA: "16:00",
        startTimeEST: "01:00pm",
        endTimeEST: "14:00",
        hasWearable: false,
        artist: Artists["MusicaW3"],
      },
      {
        id: 36,
        title: "Thug Shells",
        subtitle: "Main Stage set with merch",
        stage: "Main Stage",
        startTime: "21:00",
        endTime: "22:00",
        timeSlotStart: 11,
        timeSlotEnd: 11,
        duration: 1,
        startTimePST: "14:00",
        endTimePST: "15:00",
        startTimeCET: "10:00pm",
        endTimeCET: "23:00",
        startTimeBA: "06:00pm",
        endTimeBA: "19:00",
        startTimeEST: "04:00pm",
        endTimeEST: "17:00",
        hasWearable: true,
        artist: Artists["Thug Shells"],
      },
      {
        id: 37,
        title: "MiaMakesMusic",
        subtitle: "Main Stage set",
        stage: "Main Stage",
        startTime: "22:00",
        endTime: "23:00",
        timeSlotStart: 12,
        timeSlotEnd: 12,
        duration: 1,
        startTimePST: "15:00",
        endTimePST: "16:00",
        startTimeCET: "11:00pm",
        endTimeCET: "00:00",
        startTimeBA: "07:00pm",
        endTimeBA: "20:00",
        startTimeEST: "05:00pm",
        endTimeEST: "18:00",
        hasWearable: false,
        artist: Artists["MiaMakesMusic"],
      },
      {
        id: 38,
        title: "OfficeDrummer",
        subtitle: "Main Stage set with merch",
        stage: "Main Stage",
        startTime: "23:00",
        endTime: "Midnight",
        timeSlotStart: 13,
        timeSlotEnd: 13,
        duration: 1,
        startTimePST: "16:00",
        endTimePST: "17:00",
        startTimeCET: "midnight",
        endTimeCET: "01:00",
        startTimeBA: "08:00pm",
        endTimeBA: "21:00",
        startTimeEST: "06:00pm",
        endTimeEST: "19:00",
        hasWearable: true,
        artist: Artists["OfficeDrummer"],
      },
      {
        id: 39,
        title: "Dr. Jaffle",
        subtitle: "Live Stage set",
        stage: "Live Stage",
        startTime: "Midnight",
        endTime: "01:00",
        timeSlotStart: 14,
        timeSlotEnd: 14,
        duration: 1,
        startTimePST: "17:00",
        endTimePST: "18:00",
        startTimeCET: "01:00am",
        endTimeCET: "02:00",
        startTimeBA: "09:00pm",
        endTimeBA: "22:00",
        startTimeEST: "07:00pm",
        endTimeEST: "20:00",
        hasWearable: false,
      },
      {
        id: 40,
        title: "MetaDJ",
        subtitle: "Live Stage set",
        stage: "Live Stage",
        startTime: "01:00",
        endTime: "02:00",
        timeSlotStart: 15,
        timeSlotEnd: 15,
        duration: 1,
        startTimePST: "18:00",
        endTimePST: "19:00",
        startTimeCET: "02:00am",
        endTimeCET: "03:00",
        startTimeBA: "10:00pm",
        endTimeBA: "23:00",
        startTimeEST: "08:00pm",
        endTimeEST: "21:00",
        hasWearable: false,
        artist: Artists["MetaDJ"],
      },
      {
        id: 41,
        title: "aKIDcalledBEAST Party",
        subtitle: "Party with Crypt0M1notaur, DJ vAPED & Jambert91",
        stage: "aKIDcalledBEAST Party Pad",
        startTime: "02:00",
        endTime: "05:00",
        timeSlotStart: 16,
        timeSlotEnd: 16,
        duration: 3,
        startTimePST: "19:00",
        endTimePST: "20:00",
        startTimeCET: "03:00am",
        endTimeCET: "04:00",
        startTimeBA: "11:00pm",
        endTimeBA: "00:00",
        startTimeEST: "09:00pm",
        endTimeEST: "22:00",
        hasWearable: false,
        artist: Artists["aKIDcalledBEAST"],
      },
      {
        id: 42,
        title: "Newtro Live Session",
        subtitle: "Live sessions at the Newtro Arts Party Pad",
        stage: "Newtro Arts Party Pad",
        startTime: "05:00",
        endTime: "07:00",
        timeSlotStart: 19,
        timeSlotEnd: 19,
        duration: 2,
        startTimePST: "19:00",
        endTimePST: "20:00",
        startTimeCET: "03:00am",
        endTimeCET: "04:00",
        startTimeBA: "11:00pm",
        endTimeBA: "00:00",
        startTimeEST: "09:00pm",
        endTimeEST: "22:00",
        hasWearable: false,
        artist: Artists["Newtro Arts"],
      },
      {
        id: 43,
        title: "Meta Tribe Afterparty",
        subtitle: "Keep partying at Meta Tribe Plaza (109,50)",
        stage: "Meta Tribe Plaza",
        startTime: "07:00",
        endTime: "09:00",
        timeSlotStart: 21,
        timeSlotEnd: 21,
        duration: 2,
        startTimePST: "17:00",
        endTimePST: "18:00",
        startTimeCET: "01:00am",
        endTimeCET: "02:00",
        startTimeBA: "09:00pm",
        endTimeBA: "22:00",
        startTimeEST: "07:00pm",
        endTimeEST: "20:00",
        hasWearable: false,
      },
      {
        id: 43,
        title: "Interval",
        subtitle: "Time to hunt the 20 gifts hidden in Music Festival Plaza",
        stage: "Festival Plaza",
        startTime: "09:00",
        endTime: "10:00",
        timeSlotStart: 23,
        timeSlotEnd: 23,
        duration: 1,
        startTimePST: "20:00",
        endTimePST: "21:00",
        startTimeCET: "04:00am",
        endTimeCET: "05:00",
        startTimeBA: "12:00am",
        endTimeBA: "01:00",
        startTimeEST: "10:00pm",
        endTimeEST: "23:00",
        hasWearable: false,
      },
    ],
  },
  "dec-6": {
    "Main Stage": [
      {
        id: 44,
        title: "Interval",
        subtitle: "Hunt the 19 gifts hidden in the Music Festival Plaza",
        stage: "Gift Shop",
        startTime: "10:00",
        endTime: "11:00",
        timeSlotStart: 0,
        timeSlotEnd: 0,
        duration: 1,
        startTimePST: "04:00",
        endTimePST: "05:00",
        startTimeCET: "12:00am",
        endTimeCET: "01:00",
        startTimeBA: "08:00am",
        endTimeBA: "09:00",
        startTimeEST: "06:00am",
        endTimeEST: "07:00",
        hasWearable: false,
      },
      {
        id: 42,
        title: "Retro Partea Pad",
        subtitle: "Facemoon Gallery warmup with DJ Abillitea (-117,71)",
        stage: "Facemoon Gallery",
        startTime: "11:00",
        endTime: "Midday",
        timeSlotStart: 1,
        timeSlotEnd: 1,
        duration: 1,
        startTimePST: "04:00",
        endTimePST: "05:00",
        startTimeCET: "12:00am",
        endTimeCET: "01:00",
        startTimeBA: "08:00am",
        endTimeBA: "09:00",
        startTimeEST: "06:00am",
        endTimeEST: "07:00",
        hasWearable: false,
      },
      {
        id: 44,
        title: "Interval",
        subtitle: "Time to hunt the 20 gifts hidden in Music Festival Plaza",
        stage: "Gift Shop",
        startTime: "Midday",
        endTime: "16:00",
        timeSlotStart: 2,
        timeSlotEnd: 2,
        duration: 4,
        startTimePST: "04:00",
        endTimePST: "05:00",
        startTimeCET: "12:00am",
        endTimeCET: "01:00",
        startTimeBA: "08:00am",
        endTimeBA: "09:00",
        startTimeEST: "06:00am",
        endTimeEST: "07:00",
        hasWearable: false,
      },
      {
        id: 43,
        title: "Hape Party",
        subtitle: "DJs at the Hape Party Pad",
        stage: "Hape Party Pad",
        startTime: "16:00",
        endTime: "18:00",
        timeSlotStart: 6,
        timeSlotEnd: 6,
        duration: 2,
        startTimePST: "09:00",
        endTimePST: "10:00",
        startTimeCET: "05:00pm",
        endTimeCET: "18:00",
        startTimeBA: "01:00pm",
        endTimeBA: "14:00",
        startTimeEST: "11:00am",
        endTimeEST: "12:00",
        hasWearable: false,
        artist: Artists["Hape"],
      },
      {
        id: 45,
        title: "MusicaW3 Party Sessions",
        subtitle: "DJ Djeriko spins darkprog at the MusicaW3 Party Pad",
        stage: "MusicaW3 Party Pad",
        startTime: "18:00",
        endTime: "21:00",
        timeSlotStart: 8,
        timeSlotEnd: 8,
        duration: 3,
        startTimePST: "11:00",
        endTimePST: "12:00",
        startTimeCET: "07:00pm",
        endTimeCET: "20:00",
        startTimeBA: "03:00pm",
        endTimeBA: "16:00",
        startTimeEST: "01:00pm",
        endTimeEST: "14:00",
        hasWearable: false,
        artist: Artists["MusicaW3"],
      },
      {
        id: 48,
        title: "ABC Live Tour",
        subtitle: "Join the ABC community on a special live tour",
        stage: "Live Stage",
        startTime: "21:00",
        endTime: "22:00",
        timeSlotStart: 11,
        timeSlotEnd: 11,
        duration: 1,
        startTimePST: "14:00",
        endTimePST: "15:00",
        startTimeCET: "10:00pm",
        endTimeCET: "23:00",
        startTimeBA: "06:00pm",
        endTimeBA: "19:00",
        startTimeEST: "04:00pm",
        endTimeEST: "17:00",
        hasWearable: false,
      },
      {
        id: 49,
        title: "Dúo Dò",
        subtitle: "Main Stage set with merch",
        stage: "Main Stage",
        startTime: "22:00",
        endTime: "23:00",
        timeSlotStart: 12,
        timeSlotEnd: 12,
        duration: 1,
        startTimePST: "15:00",
        endTimePST: "16:00",
        startTimeCET: "11:00pm",
        endTimeCET: "00:00",
        startTimeBA: "07:00pm",
        endTimeBA: "20:00",
        startTimeEST: "05:00pm",
        endTimeEST: "18:00",
        hasWearable: true,
        artist: Artists["Dúo Dø"],
      },
      {
        id: 50,
        title: "NaNa The Ape",
        subtitle: "Main Stage set with merch",
        stage: "Main Stage",
        startTime: "23:00",
        endTime: "Midnight",
        timeSlotStart: 13,
        timeSlotEnd: 13,
        duration: 1,
        startTimePST: "16:00",
        endTimePST: "17:00",
        startTimeCET: "Midnight",
        endTimeCET: "01:00",
        startTimeBA: "08:00pm",
        endTimeBA: "21:00",
        startTimeEST: "06:00pm",
        endTimeEST: "19:00",
        hasWearable: true,
        artist: {
          name: "NaNa The Ape",
          bio: "NaNa the Ape is a multi-talented virtual artist, singer-songwriter, and DJ, known for her deep, soulful vocals and genre-blending sound that fuses R&B, Afrobeats, and EDM. As a prominent figure in the metaverse music scene, she has performed at major virtual festivals, bringing an electrifying energy to every set. With a passion for pushing creative boundaries, NaNa continues to captivate global audiences, bridging the gap between digital culture and live performance.",
          socials: {
            twitter: "https://x.com/nanatheape",
            instagram: "https://instagram.com/nanatheape",
            twitch: null,
            website: null,
          },
          image: NaNaTheApeImage,
        },
      },
      {
        id: 51,
        title: "Steve Sai",
        subtitle: "Main Stage set with merch",
        stage: "Main Stage",
        startTime: "Midnight",
        endTime: "01:00",
        timeSlotStart: 14,
        timeSlotEnd: 14,
        duration: 1,
        startTimePST: "17:00",
        endTimePST: "18:00",
        startTimeCET: "01:00am",
        endTimeCET: "02:00",
        startTimeBA: "09:00pm",
        endTimeBA: "22:00",
        startTimeEST: "07:00pm",
        endTimeEST: "20:00",
        hasWearable: true,
        artist: Artists["Steve Sai"],
      },
      {
        id: 52,
        title: "Newtro Live AV Sessions",
        subtitle: "Live sessions at the Newtro Arts Party Pad",
        stage: "Newtro Arts Party Pad",
        startTime: "01:00",
        endTime: "03:00",
        timeSlotStart: 15,
        timeSlotEnd: 15,
        duration: 2,
        startTimePST: "18:00",
        endTimePST: "19:00",
        startTimeCET: "02:00am",
        endTimeCET: "03:00",
        startTimeBA: "10:00pm",
        endTimeBA: "23:00",
        startTimeEST: "08:00pm",
        endTimeEST: "21:00",
        hasWearable: false,
      },
      {
        id: 53,
        title: "AFTER-HOURS",
        subtitle:
          "Epic 6-hour afterparty at the 4RC Night Club (40,55) with Crypt0M1notaur, Austin De Chêne & Silvio De Candia.",
        stage: "4RC Night Club",
        startTime: "03:00",
        endTime: "09:00",
        timeSlotStart: 17,
        timeSlotEnd: 17,
        duration: 6,
        startTimePST: "19:00",
        endTimePST: "20:00",
        startTimeCET: "03:00am",
        endTimeCET: "04:00",
        startTimeBA: "11:00pm",
        endTimeBA: "00:00",
        startTimeEST: "09:00pm",
        endTimeEST: "22:00",
        hasWearable: false,
      },
      {
        id: 53,
        title: "Close",
        subtitle: "See you again on Dec 11 for a special launch party",
        stage: "Genesis Plaza",
        startTime: "09:00",
        endTime: "10:00",
        timeSlotStart: 23,
        timeSlotEnd: 23,
        duration: 1,
        startTimePST: "20:00",
        endTimePST: "21:00",
        startTimeCET: "04:00am",
        endTimeCET: "05:00",
        startTimeBA: "12:00am",
        endTimeBA: "01:00",
        startTimeEST: "10:00pm",
        endTimeEST: "23:00",
        hasWearable: false,
      },
    ],
  },
}

const dateOptions = [
  { key: "dec-3", date: "DEC 3", label: "Day One" },
  { key: "dec-4", date: "DEC 4", label: "Day Two" },
  { key: "dec-5", date: "DEC 5", label: "Day Three" },
  { key: "dec-6", date: "DEC 6", label: "Day Four" },
] as const

export type { ScheduleEvent, StageSchedule, DaySchedule }

export { timeSlots, stages, scheduleData, dateOptions, convertToPST }
